title: "Quickly get your Quarto HTML theme in order"
author: "Greg Swinehart / Posit, PBC"
format: 
  revealjs:
    theme: theme.scss
    menu: false



title-slide-attributes:
    data-background-color: "#ffffff"
    data-color: "#404041"


project:
  resources:
    # Explicitly call out the images folder to include background images in _build.
    - "*.mp4"
    - "*.png"
    - "*.jpg"
  output-dir: _build